# Generated by Django 3.2.7 on 2021-09-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('about', models.TextField(null=True, verbose_name='متن درباره ما')),
                ('service_img_1', models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس اول')),
                ('service_title_1', models.CharField(max_length=200, verbose_name='عنوان سرویس اول')),
                ('service_description_1', models.TextField(null=True, verbose_name='توضیحات سرویس اول')),
                ('service_img_2', models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس دوم')),
                ('service_title_2', models.CharField(max_length=200, verbose_name='عنوان سرویس دوم')),
                ('service_description_2', models.TextField(null=True, verbose_name='توضیحات سرویس دوم')),
                ('service_img_3', models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس سوم')),
                ('service_title_3', models.CharField(max_length=200, verbose_name='عنوان سرویس سوم')),
                ('service_description_3', models.TextField(null=True, verbose_name='توضیحات سرویس سوم')),
                ('service_img_4', models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس چهارم')),
                ('service_title_4', models.CharField(max_length=200, verbose_name='عنوان سرویس چهارم')),
                ('service_description_4', models.TextField(null=True, verbose_name='توضیحات سرویس چهارم')),
                ('keywords', models.CharField(max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('seo_description', models.TextField(null=True, verbose_name='توضیحات سئو')),
            ],
            options={
                'verbose_name': 'مشخصات صفحه درباره ما',
                'verbose_name_plural': 'تنظیمات صفحه درباره ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='تلفن')),
                ('keywords', models.CharField(max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('seo_description', models.TextField(null=True, verbose_name='توضیحات سئو')),
            ],
            options={
                'verbose_name': 'مشخصات صفحه تماس با ما',
                'verbose_name_plural': 'تنظیمات صفحه تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='DoctorsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام دکتر')),
                ('job', models.CharField(max_length=300, verbose_name='تخصص')),
                ('description', models.TextField(null=True, verbose_name='توضیحات تکمیلی')),
            ],
            options={
                'verbose_name': 'دکتر',
                'verbose_name_plural': 'دکترها',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سایت')),
                ('about_us', models.TextField(null=True, verbose_name='متن خلاصه درباره ما')),
                ('keywords', models.CharField(max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('seo_description', models.TextField(null=True, verbose_name='توضیحات سئو')),
            ],
            options={
                'verbose_name': 'مشخصات صفحه خانه',
                'verbose_name_plural': 'تنظیمات صفحه خانه',
            },
        ),
    ]
