# Generated by Django 3.2.7 on 2021-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان عکس')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'گالری عکس',
                'verbose_name_plural': 'گالری عکس ها',
            },
        ),
    ]
