# Generated by Django 3.2.7 on 2021-09-08 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegallery',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
    ]
