# Generated by Django 3.2.7 on 2021-09-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_homegallery_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('description', models.TextField(null=True, verbose_name='توضیحات تکمیلی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('instagram', models.URLField(null=True)),
                ('telegram', models.URLField(null=True)),
                ('whatsapp', models.URLField(null=True)),
                ('email', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
    ]
