# Generated by Django 3.2.7 on 2021-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_siteinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='logo',
            field=models.ImageField(null=True, upload_to='site_logo', verbose_name='لوگو'),
        ),
    ]
