# Generated by Django 3.2.7 on 2021-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_siteinformation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
