# Generated by Django 3.2.7 on 2021-09-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='description',
        ),
    ]
