# Generated by Django 3.2.7 on 2021-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210911_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homegallery',
            name='service_description_1',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_description_2',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_description_3',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_description_4',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_img_1',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_img_2',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_img_3',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_img_4',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_title_1',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_title_2',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_title_3',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='service_title_4',
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_description_1',
            field=models.TextField(null=True, verbose_name='توضیحات سرویس اول'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_description_2',
            field=models.TextField(null=True, verbose_name='توضیحات سرویس دوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_description_3',
            field=models.TextField(null=True, verbose_name='توضیحات سرویس سوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_description_4',
            field=models.TextField(null=True, verbose_name='توضیحات سرویس چهارم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_img_1',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس اول'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_img_2',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس دوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_img_3',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس سوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_img_4',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر سرویس چهارم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title_1',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان سرویس اول'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title_2',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان سرویس دوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title_3',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان سرویس سوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title_4',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان سرویس چهارم'),
        ),
    ]
