# Generated by Django 3.2.7 on 2021-09-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210911_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='service_description_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_description_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_description_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_description_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_img_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_img_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_img_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_img_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_title_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_title_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_title_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_title_4',
        ),
    ]
