# Generated by Django 3.2.7 on 2021-09-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210911_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان سایت'),
        ),
    ]
