# Generated by Django 3.2.7 on 2021-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_siteinformation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='متن پیام'),
        ),
    ]
