# Generated by Django 3.2.7 on 2021-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_contactusform_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusform',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
