# Generated by Django 3.2.7 on 2021-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_contactusform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='category',
            field=models.CharField(choices=[('h', 'کاشت مو'), ('e', 'کاشت ابرو'), ('m', 'مزوتراپی'), ('b', 'بوتاکس')], max_length=1, verbose_name='نوع درخواست'),
        ),
    ]
