# Generated by Django 3.2.7 on 2021-09-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_reserve_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='keywords',
            field=models.CharField(help_text='* الزامی: برای جداسازی کلمات کلیدی از , استفاده کنید.', max_length=300, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='seo_description',
            field=models.TextField(help_text='* الزامی: تعداد کارکترها برای نمایش بهتر، باید بین 50 الی 160 کارکتر باشد.', max_length=200, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='keywords',
            field=models.CharField(help_text='* الزامی: برای جداسازی کلمات کلیدی از , استفاده کنید.', max_length=300, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='seo_description',
            field=models.TextField(help_text='* الزامی: تعداد کارکترها برای نمایش بهتر، باید بین 50 الی 160 کارکتر باشد.', max_length=200, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(help_text='* الزامی: برای جداسازی کلمات کلیدی از , استفاده کنید.', max_length=300, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description',
            field=models.TextField(help_text='* الزامی: تعداد کارکترها برای نمایش بهتر، باید بین 50 الی 160 کارکتر باشد.', max_length=200, null=True, verbose_name='توضیحات سئو'),
        ),
    ]
