# Generated by Django 3.2.7 on 2021-09-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210915_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegallery',
            name='image',
            field=models.ImageField(help_text='* پیشنهادی: اندازه تصویر پیشنهادی 600 * 800', upload_to='gallery', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='logo',
            field=models.ImageField(help_text='* پیشنهادی: حداکثر ارتفاع 80', null=True, upload_to='site_logo', verbose_name='لوگو'),
        ),
    ]
