# Generated by Django 3.2.7 on 2021-10-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210926_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='logo_footer',
            field=models.ImageField(help_text='* پیشنهادی: حداکثر ارتفاع 80 پیکسل', null=True, upload_to='site_logo', verbose_name='لوگو فوتر'),
        ),
    ]
