# Generated by Django 3.2.7 on 2021-09-04 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس تگ')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس مقاله')),
                ('description', models.TextField(verbose_name='متن مقاله')),
                ('image', models.ImageField(upload_to='article', verbose_name='عکس اصلی')),
                ('image_thumbnail', models.ImageField(upload_to='article', verbose_name='عکس بندانگشتی')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت')),
                ('keywords', models.CharField(max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('seo_description', models.TextField(null=True, verbose_name='توضیحات سئو')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='blogs', to='blogs.Category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(related_name='blogs', to='blogs.Tags', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish'],
            },
        ),
    ]
