# Generated by Django 3.2.7 on 2021-09-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_article_seo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='* پیشنهادی: اندازه تصویر اصلی پیشنهادی 515 * 850', upload_to='article', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_thumbnail',
            field=models.ImageField(help_text='* پیشنهادی: اندازه تصویر بندانگشتی پیشنهادی 200 * 300', upload_to='article', verbose_name='عکس بندانگشتی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(help_text='* الزامی: برای جداسازی کلمات کلیدی از , استفاده کنید.', max_length=300, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.TextField(help_text='* الزامی: تعداد کارکترها برای نمایش بهتر، باید بین 50 الی 160 کارکتر باشد.', max_length=200, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='* الزامی: حتما از حروف انگلیسی استفاده و فاصله ها با - پر شود.', max_length=200, unique=True, verbose_name='آدرس مقاله'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='* الزامی: حتما از حروف انگلیسی استفاده و فاصله ها با - پر شود.', max_length=200, unique=True, verbose_name='آدرس دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(help_text='* الزامی: حتما از حروف انگلیسی استفاده و فاصله ها با - پر شود.', max_length=200, unique=True, verbose_name='آدرس تگ'),
        ),
    ]
