# Generated by Django 3.2.7 on 2021-09-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20210915_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(help_text='* جایگاه برای اولویت نمایش در لیست دسته بندی ها است', verbose_name='جایگاه'),
        ),
    ]
