# Generated by Django 3.2.7 on 2021-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20210926_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blogs.IPAddress', verbose_name='بازدیدها'),
        ),
    ]
