# Generated by Django 3.2.7 on 2021-09-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20210926_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.article')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='blogs.BlogHit', to='blogs.IPAddress', verbose_name='بازدیدها'),
        ),
    ]
